#!/usr/bin/env bash
#MISE description="Install MOD locally"
#MISE depends=["build"]
set -euo pipefail

mod_name=$(jq -r .name info.json)
mod_version=$(jq -r .version info.json)
archive="dist/${mod_name}_${mod_version}.zip"
mod_dir=$(factorix path --json | jq -r .mod_dir)
cp "$archive" "$mod_dir"
