name: "Detect latest version"
description: "Detect and set information of the latest version of the MOD in concern"
author: "sakuro"
inputs:
  mod_name:
    description: "Name of the MOD"
    required: true
outputs:
  download_url:
    description: "Download URL of the latest version of the MOD"
  file_name:
    description: "File name of the latest version of the MOD"
  released_at:
    description: "Release date of the latest version of the MOD in ISO8601"
  sha1:
    description: "SHA1 digest of the latest version of the MOD"
  version:
    description: "Latest version of the MOD"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.mod_name }}
