#!/bin/sh

PLAYER_DATA_JSON="$HOME/Library/Application Support/factorio/player-data.json"

echo "${SERVICE_USERNAME:-$(jq -rM '."service-username"' < "${PLAYER_DATA_JSON}")}"
echo "${SERVICE_TOKEN:-$(jq -rM '."service-token"' < "${PLAYER_DATA_JSON}")}"
