#!/bin/sh

set -- $(./tools/api-credentials)
username=$1
token=$2

file_name="$(jq -rM .file_name < .latest-version)"
download_url="$(jq -rM .download_url < .latest-version)"

curl -sLo "${file_name}" "https://mods.factorio.com/${download_url}?username=${username}&token=${token}"
