name: Create update-locale PR
on: [workflow_dispatch]
jobs:
  Create-Update-Locale-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git and gh CLI
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
      - name: Fetch information about the latest version
        id: latest_version
        uses: ./.github/actions/latest-version
        with:
          mod_name: nullius
      - name: Download latest MOD
        env:
          FILE_NAME: ${{ steps.latest_version.outputs.file_name }}
          DOWNLOAD_URL: ${{ steps.latest_version.outputs.download_url }}
          USERNAME: ${{ secrets.SERVICE_USERNAME }}
          TOKEN: ${{ secrets.SERVICE_TOKEN }}
        run: |
          curl -sLo "${FILE_NAME}" "${DOWNLOAD_URL}?username=${USERNAME}&token=${TOKEN}"
      - name: Update locale/en files
        env:
          FILE_NAME: ${{ steps.latest_version.outputs.file_name }}
        run: |
          for file in $(unzip -Z1 "${FILE_NAME}" | grep locale/en/.*\.cfg); do
            unzip -p "${FILE_NAME}" "${file}" | tr -d '\r' > "locale/en/$(basename "${file}")"
          done
          git status -sb
      - name: Create a PR on any changes in locale/en
        env:
          FULL_NAME: ${{ steps.latest_version.outputs.full_name }}
          PR_BRANCH: update-locale/en-from-${{ steps.latest_version.outputs.full_name }}
          GITHUB_TOKEN: ${{ secrets.GH_CLI_TOKEN }}
        run: |
          [[ -z "$(git status --porcelain=v2 --untracked locale/en)" ]] && exit 0
          (rm -f info.json && jq -M '.dependencies=["${{ steps.latest_version.outputs.mod_name }} >= ${{ steps.latest_version.outputs.version }}"]' > info.json) < info.json
          git switch -c "${PR_BRANCH}"
          git add locale/en info.json
          git commit -m "Update locale/en from ${FULL_NAME}"
          git push origin "${PR_BRANCH}"
          gh pr create --draft --title "Update locale/en from ${FULL_NAME}" --body "This PR is automatically created by the GitHub Action workflow ${{ github.workflow }}"
