name: Create update-locale PR
on: [workflow_dispatch]
jobs:
  Create-Update-Locale-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Fetch information about the latest version
        id: latest
        uses: ./.github/actions/latest-version
        with:
          mod_name: nullius
      - name: Output result
        run:
          echo DOWNLOAD_URL=${{ steps.latest.outputs.download_url }}
          echo FILE_NAME=${{ steps.latest.outputs.file_name }}
          echo RELEASED_AT=${{ steps.latest.outputs.released_at }}
          echo SHA1=${{ steps.latest.outputs.shat1 }}
          echo VERSION=${{ steps.latest.outputs.version }}
