name: Create update-locale PR
on: [workflow_dispatch]
jobs:
  Create-Update-Locale-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Fetch information about the latest version
        id: latest_version
        uses: ./.github/actions/latest-version
        with:
          mod_name: nullius
      - name: Download
        run: |
          file_name="${{ steps.latest_version.outputs.file_name }}"
          download_url="${{ steps.latest_version.outputs.download_url }}"
          username="${{ secrets.SERVICE_USERNAME }}"
          token="${{ secrets.SERVICE_TOKEN }}"
          curl -sLo "${file_name}" "${download_url}?username=${username}&token=${token}"
          ls -l
