name: Create update-locale PR
on: [workflow_dispatch]
jobs:
  Create-Update-Locale-PR:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Configure git and gh CLI
        uses: git-actions/set-user@v1
      - name: Fetch information about the latest version
        id: latest_version
        uses: ./.github/actions/latest-version
        with:
          mod_name: nullius
      - name: Download latest MOD
        run: |
          curl -sLo "${{ steps.latest_version.outputs.file_name }}" "${{ steps.latest_version.outputs.download_url }}?username=${{ secrets.SERVICE_USERNAME }}&token=${{ secrets.SERVICE_TOKEN }}"
      - name: Update locale/en files
        run: |
          for file in $(unzip -Z1 "${{ steps.latest_version.outputs.file_name }}" | grep locale/en/.*\.cfg); do
            unzip -p "${{ steps.latest_version.outputs.file_name }}" "${file}" | tr -d '\r' > "locale/en/$(basename "${file}")"
          done
          git status -sb
      - name: Create a PR on any changes in locale/en
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          [[ -z "$(git status --porcelain=v2 --untracked locale/en)" ]] && exit 0
          (rm -f info.json && jq -M '.dependencies=["${{ steps.latest_version.outputs.mod_name }} >= ${{ steps.latest_version.outputs.version }}"]' > info.json) < info.json
          git switch -c "update-locale/en-from-${{ steps.latest_version.outputs.full_name }}"
          git add locale/en info.json
          git commit -m "Update locale/en from ${{ steps.latest_version.outputs.full_name }}"
          git push origin "update-locale/en-from-${{ steps.latest_version.outputs.full_name }}"
          gh pr create --draft --title "Update locale/en from ${{ steps.latest_version.outputs.full_name }}" --body "This PR is automatically created by the GitHub Action workflow ${{ github.workflow }}"
